<?php
namespace app\agent\controller;
use cmf\controller\AdminBaseController;
use think\Db;

/**
 * Created by PhpStorm.
 * User: YTH
 * Date: 2021/7/16
 * Time: 5:15 下午
 * Name:
 */
class BaseController extends AdminBaseController{
    public function _initialize()
    {
        $session_admin_id = session('AGENT_ID');
        if (!empty($session_admin_id)) {
            $user = Db::name('agent')->where(['id' => $session_admin_id])->find();
            $config_log = load_cache('config');

            $this->assign("config_log", $config_log);
            $module     = $this->request->module();
            $controller = $this->request->controller();
            $action     = $this->request->action();
            $rule       = $module . $controller . $action;
            $notRequire = ["agentUseruserinfopost","agentIndexindex","agentIndexstatistical", "agentUserannouncement","agentUserindex"];
            if (!in_array($rule, $notRequire)) {
                if ($user['agent_level'] !=1 && empty($user['mobile'])) {
                    // 手机号必填
                    $this->error("请进入个人中心绑定手机号！",url("agent/user/index"));
                }
            }
            /* if (!$this->checkAccess($session_admin_id)) {
                 $this->error("您没有访问权限！");
             }*/
            $this->assign("admin", $user);
        } else {
            if ($this->request->isPost()) {
                $this->error(lang('Not_logged_in'), url("/agent/public/login"));
            } else {
                header("Location:" . url("/agent/public/login"));
                exit();
            }
        }
        //parent::_initialize(); // TODO: Change the autogenerated stub
    }
}